# Generated by Django 4.1.1 on 2022-10-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Контакт", "verbose_name_plural": "Контакты"},
        ),
        migrations.AlterField(
            model_name="contact",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="e-mail"),
        ),
    ]
