# Generated by Django 4.1.1 on 2022-09-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_actors_alter_movie_directors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={
                "verbose_name": "Актеры и fрежиссеры",
                "verbose_name_plural": "Актеры и режиссеры",
            },
        ),
    ]
