# Generated by Django 4.1.1 on 2022-10-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_actor_options"),
    ]

    operations = [
        migrations.RemoveField(model_name="actor", name="age",),
        migrations.AddField(
            model_name="actor",
            name="date_of_birth",
            field=models.DateField(null=True, verbose_name="Дата рождения"),
        ),
    ]
