# Generated by Django 4.1.1 on 2022-10-08 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_remove_actor_age_actor_date_of_birth"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rattingstar",
            options={
                "ordering": ["-value"],
                "verbose_name": "Звезда рейтинга",
                "verbose_name_plural": "Звезды рейтинга",
            },
        ),
    ]
